build:
  environment:
    php: '8'
  dependencies:
    before:
      - composer install
  tests:
    override:
      -
        command: 'composer phpunit -- --coverage-clover=.coverage.xml'
        coverage:
          file: '.coverage.xml'
          format: 'clover'
filter:
  excluded_paths:
    - "database/"
    - "config/"
    - "tests/"
